### ISSUE TITLE
Scale the icons when viewBox and width/height differs

### ISSUE THREAD

**Issue by nfroidure** [nfroidure/svgicons2svgfont#9]
The process should be:
- set the viewbox size with the viewBox attribute if it exists then, read x y width and height attributes to scale the icon to the desired width/height being preserveAspectRatio aware
- otherwise, use x y width and height attributes
- finally if none of this attributes are present, maybe deduct from the drawed elements the icon bounds ?

Specs:
http://www.w3.org/TR/SVG/coords.html#ViewBoxAttribute
http://www.w3.org/TR/SVG/coords.html#PreserveAspectRatioAttribute

**Comment by dongyuwei** [comment]
+1

**Comment by nfroidure** [comment]
Done https://github.com/nfroidure/svgicons2svgfont/commit/44e3dd6853c7f27a097428629a7b6a4c0042bb4f

**Comment by aseem2625** [comment]
Hey @nfroidure this actually didn't solve the issue..
Some [other guy](https://github.com/nfroidure/gulp-iconfont/issues/143#issuecomment-315591252) also faced this issue with latest version.

**Comment by seanking2919** [comment]
Fantasticon has faced [similar issues](https://github.com/tancredi/fantasticon/issues/11) regarding fonts not being vertically centered properly in some cases.

**Comment by nfroidure** [comment]
The code for calculating bounds sits here : https://github.com/nfroidure/svg-pathdata/blob/master/src/SVGPathDataTransformer.ts#L521-L619
